### ISSUE TITLE
TRANS2QUIK_CONNECT

### ISSUE THREAD

**Issue by javas** [Enfernuz/JavaTrans2Quik#1]
Подскажи, пожалуйста, где взять последнюю версию trans2quik.dll? Я так понимаю есть версия 1.2 (x86), 1.3 (x64). И еще у вас некоторые функции, например, TRANS2QUIK_CONNECT , возвращают текст ошибки в buffer (byte[]). Как оттуда текст получить? String.valueOf(buffer), возвращает текст такого рода ( [B@2b164752 ).

**Comment by Enfernuz** [comment]
1.2 - это API для версий QUIK 6.3+, 1.3 -- для 64-битных версий 7.0+. Обёртка была сделана на основе линейки 1.2 и с библиотекой 1.3 работать не будет (требуется дописать/переписать обёртку).
Как преобразовать массив байт (byte[]) в строку (java.lang.String) -- куча результатов в гугле, уверяю :)
Из простого попробуйте метод из JNA:
com.sun.jna.Native.toString(byte[] byteArray, String encoding)
Например, String message = Native.toString(buffer, "cp1251").

**Comment by javas** [comment]
Я не переписывал, с 1.3 заработало, для функций TRANS2QUIK_CONNECT, TRANS2QUIK_SEND_ASYNC_TRANSACTION, TransactionReplyCallback . Спасибо, текст удалось достать, я просто с jna не очень дружу. А вообще ребята из Arqatech где-нибудь выкладывают официальную dll с документацией, помимо ссылок на их форумах?

**Comment by Enfernuz** [comment]
Странно, что заработало :)
API для импорта транзакций они выкладывают на сайте:
https://arqatech.com/ru/support/files/
Раздел "KeyGen, прочие утилиты и документация".

**Comment by javas** [comment]
Спасибо!
